name: sifa_farmer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  image_picker: ^1.0.4
  translator: 1.0.3+1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.3
  crop_your_image: ^1.0.3 
  camera: ^0.10.5+9  
  camera_web: ^0.3.3   
  
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
